#
# This build script
# Author: Yolier Galan Tasse <gallegogt@gmail.com>
#
# For any issues of feedback report it at Github
#
# Json Pack project
#

language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8
os:
    - linux
    - osx

compiler:
    - gcc

before_install:
    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev

install:
    # g++4.8.1
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
    - mkdir build/
    - cd build/
    - cmake ..  -DJSONPACK_BUILD_EXAMPLES=ON -DJSONPACK_BUILD_TEST=ON
    - cmake --build . --clean-first
    - make test

